CREATE DATABASE IF NOT EXISTS pos_auth;
CREATE DATABASE IF NOT EXISTS pos_menu;
CREATE DATABASE IF NOT EXISTS pos_order;
CREATE DATABASE IF NOT EXISTS pos_payment;
CREATE DATABASE IF NOT EXISTS pos_table;

GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
FLUSH PRIVILEGES;
